### ISSUE TITLE
Windows XP GUI Glitch

### ISSUE THREAD

**Issue by ryanginnelly252** [brazier19971/Unsilenced-Mk2#1]
![image](https://user-images.githubusercontent.com/76879367/133884421-3b69f30e-4605-4434-8c78-863f5adb058c.png)
This happens when I run it on XP SP3.
If possible, adjust the buttons to make them a big higher up! 👍

**Comment by brazier19971** [comment]
Issue seems to be caused by your display scaling settings, I haven’t had this issue on XP

**Comment by ryanginnelly252** [comment]
Huh, Not sure as I just recieved the laptop with it's driver disk. Installed that and nothing changed
